development: &default
  adapter: postgresql
  database: jobo_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: jobo_test

cucumber:
  <<: *test